services:
  y_money-app:
    build: ./y_money
    volumes:
      - ./y_money:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - y_money_network

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - y_money_network

  redis:
    image: redis:7.0
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - y_money_network

networks:
  y_money_network:
    driver: bridge

volumes:
  db_data:
  redis_data: