# Generated by Django 6.0.3 on 2026-03-13 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('bank_account', 'Bank Account'), ('credit_card', 'Credit Card'), ('savings', 'Savings'), ('investment', 'Investment'), ('other', 'Other')], default='cash', max_length=12)),
                ('currency', models.CharField(choices=[('pln', 'Polish Złoty'), ('eur', 'Euro'), ('czk', 'Czech Koruna'), ('usd', 'United States dollar')], default='pln', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='users.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['owner'], name='wallets_wal_owner_i_1b30e4_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_wallet')],
            },
        ),
    ]
