# Generated by Django 6.0.3 on 2026-04-06 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('users', '0002_alter_profile_user'),
        ('wallets', '0002_wallet_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recipient_friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_external_transfers', to='users.profile'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='wallets.wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_mode',
            field=models.CharField(blank=True, choices=[('internal', 'Internal'), ('external', 'External')], max_length=10, null=True),
        ),
    ]
